# theme.toml template for a Hugo theme
# See https://www.incredibleapp.top/ for an example

name = "Wenhan.Xiao"
license = "MIT"
licenselink = "https://mit-license.org/"
description = "Wenhan Custom theme for hugo"
homepage = "https://www.incredibleapp.top/"
demosite = "https://www.incredibleapp.top/"
tags = [
  "clean",
  "contact",
  "fontawesome",
  "forkawesome",
  "landing page",
  "onepage",
  "one page",
  "personal",
  "projects",
  "simple",
  "single page",
  "starter",
  "responsive",
  "theme"
]
features = ["cover-image", "favicon", "header-menu", "auto-scroll"]
min_version = "0.41.0"

[author]
  name = "Wenhan.Xiao"
  homepage = "https://www.incredibleapp.top/"

[original]
  name = "GhostScroll"
  homepage = "https://github.com/grmmph/GhostScroll"
  repo = "https://github.com/grmmph/GhostScroll"
